"""Create initial database schema

Revision ID: b9ccbc2609bb
Revises: 
Create Date: 2025-11-23 22:57:54.199627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9ccbc2609bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('institutions_unique'), 'institutions', type_='unique')
    op.alter_column('students', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'students', 'institutions', ['institution_id'], ['id'])
    op.create_foreign_key(None, 'students', 'users', ['teacher_id'], ['id'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('parent', 'teacher', 'receptionist', 'admin', name='userrole'),
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('invited', 'active', 'inactive', name='userstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'status',
               existing_type=sa.Enum('invited', 'active', 'inactive', name='userstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('parent', 'teacher', 'receptionist', 'admin', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.alter_column('students', 'institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('institutions_unique'), 'institutions', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
