"""Implement new multi-tenancy and class-based models

Revision ID: e46b5327c4eb
Revises: b9ccbc2609bb
Create Date: 2025-11-24 15:02:28.244581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e46b5327c4eb'
down_revision: Union[str, Sequence[str], None] = 'b9ccbc2609bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.drop_constraint(op.f('institutions_unique'), 'institutions', type_='unique')
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=False))
    op.alter_column('students', 'status',
               existing_type=postgresql.ENUM('in_class', 'waiting_pickup', 'departed', 'parent_is_coming', 'can_be_picked_up', 'homework_pending', name='studentstatus'),
               nullable=False)
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'students', 'classes', ['class_id'], ['id'])
    op.drop_column('students', 'institution_id')
    op.drop_column('students', 'teacher_id')
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('parent', 'teacher', 'receptionist', 'admin', 'super_admin', name='userrole'),
               nullable=False,
               postgresql_using="role::userrole"
)  # <--- 新增這一行
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('invited', 'active', 'inactive', name='userstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"),
                postgresql_using="status::userstatus"
)
    op.create_foreign_key(None, 'users', 'institutions', ['institution_id'], ['id'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'status',
               existing_type=sa.Enum('invited', 'active', 'inactive', name='userstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))              
    op.alter_column('users', 'role',
               existing_type=sa.Enum('parent', 'teacher', 'receptionist', 'admin', 'super_admin', name='userrole'),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('students', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('institution_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.alter_column('students', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('students', 'status',
               existing_type=postgresql.ENUM('in_class', 'waiting_pickup', 'departed', 'parent_is_coming', 'can_be_picked_up', 'homework_pending', name='studentstatus'),
               nullable=True)
    op.drop_column('students', 'class_id')
    op.create_unique_constraint(op.f('institutions_unique'), 'institutions', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
